language: python

python:
 - pypy
 - pypy3
 - 2.6
 - 2.7
 - 3.2
 - 3.3
 - 3.4

install:
 - pip install pillow six
 - python setup.py install

script:
 - cd examples/helloworld/
 - ./helloworld.py

after_script:
 - pip install pep8 pyflakes
 - pep8 --statistics --count *.py
 - pyflakes *.py | tee >(wc -l)

matrix:
  fast_finish: true
